package main.util.codetester;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import main.util.filedetails.FileDetails;


/*
 * - Partial marking System
 * - Destroy .class, .txt, .exe files
 */
public class FileOutputMatcher {
	static String path_output="";//path to the output file generated by the compiler
	static String path_check="";//Path to the actual output file uploaded by the professor
	static int m;
	public FileOutputMatcher(String out,String check,int m){
		path_output = out;
		path_check = check;
		this.m = m;
	}
	
	
	public int CheckOutputs()throws IOException {
		// TODO Auto-generated method stub
		BufferedReader reader1=new BufferedReader(new FileReader(path_check));
		BufferedReader reader2=new BufferedReader(new FileReader(path_output));
		PrintWriter pw=new PrintWriter(System.out);
		String actual_output = reader1.readLine(); //This string reads the actual output file
		String output = reader2.readLine();//This String reads the output file uploaded by the student
		int lineNum=1;//The line being compared
		boolean areEqual=false;
		while(actual_output!=null&&output!=null){
			if(actual_output.equals(output)){
				//add marks
				areEqual = true;
			}else{
				areEqual = false;
				break;
			}
			actual_output = reader1.readLine();
			output = reader2.readLine();
			lineNum++;
		}
		reader1.close();
		reader2.close();
		if(areEqual){
			//pw.println("All test cases passed");
			return m;
		}else{
			//pw.println("Wrong Outputs at line = "+lineNum);
			return m;
		}
	}
	
	public void DeleteFiles() throws Exception{
		FileDetails fl=new FileDetails();
		fl.deleteSSHFiles(path_output.substring(0, path_output.lastIndexOf("/")+1));
	}
}
